language : java
jdk: oraclejdk11
services:
  - mysql
sudo: false
install: true
script: mvn clean install

before_install:
  - mysql -e 'CREATE DATABASE jag_db;'
  
  - SET PASSWORD FOR root@'localhost' = PASSWORD('ocpizza');

test:
  adapter: mysql2
  database: jag_db
  username: root
  password : ocpizza
  encoding: utf8
