language : java
jdk:
  -openjdk8
  -openjdk11
services:
  - mysql
sudo: false

test:
  - username: root
  - password: ocpizza
  - mysql -e 'CREATE DATABASE jag_db;'
install: true
dist: xenial
script: mvn verify
